In [16]:
import os.path
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.expand_frame_repr', False)

In [10]:
patient = pd.read_csv(os.path.join("data", "working_data", "week_5_data.csv")) 
air_pollution = pd.read_csv(os.path.join("data", "week_6", "cri_air_pollution.csv"))

In [11]:
patient.head()

                                     Id   BIRTHDATE DEATHDATE          SSN  DRIVERS  PASSPORT  PREFIX        FIRST         LAST  SUFFIX  MAIDEN  MARITAL   RACE    ETHNICITY GENDER                       BIRTHPLACE                        ADDRESS         CITY          STATE            COUNTY     FIPS   ZIP        LAT        LON  HEALTHCARE_EXPENSES  HEALTHCARE_COVERAGE  INCOME  CURRENT_AGE  TOTAL_CONDITIONS  TOTAL_ENCOUNTER  ASTHMA_REASON_ENCOUNTER  SYMPTOM_ENCOUNTER  EMERGENCY_ENCOUNTER  URGENT_CARE_ENCOUNTER  ASTHMA_FU_ENCOUNTER  ACTIVE_ALLERGY_COUNT  ACTIVE_MEDICATION_COUNT  ACTIVE_CAREPLAN_COUNT
0  d54a7e5d-02cc-3df8-fa87-a7133bb8dbd0  2019-05-02       NaN  999-87-5214      NaN       NaN     NaN  Ferdinand55  Mitchell808     NaN     NaN      NaN  white  nonhispanic      M        Oxford  Massachusetts  US            620 Luettgen Avenue  Easthampton  Massachusetts  Hampshire County  25015.0  1027  42.260142 -72.798090             11931.12                 0.00  168858          7.0                 1               22                        6                  3                  NaN                    NaN                  3.0                   7.0                        2                      2
1  a8f47b70-4707-d5e3-b3e3-b40c74cfc220  2016-04-05       NaN  999-86-6187      NaN       NaN     NaN     Ariel183  Emmerich580     NaN     NaN      NaN  white  nonhispanic      M  Southborough  Massachusetts  US      149 Weimann Viaduct Apt 9   Framingham  Massachusetts  Middlesex County  25017.0  1702  42.290083 -71.459564              3255.03             18441.83   12983         10.0                 6               33                        4                  5                  2.0                    3.0                  3.0                   8.0                        2                      3
2  1ebb8037-f48c-5aae-61b8-bca2b28fd86e  2018-04-16       NaN  999-56-5258      NaN       NaN     NaN      Lisa683    Durgan499     NaN     NaN      NaN  white  nonhispanic      F        Quincy  Massachusetts  US  533 Wuckert Junction Suite 37   Wilmington  Massachusetts  Middlesex County  25017.0  1887  42.573334 -71.150584              8051.91              8174.95  141803          8.0                 3               31                        1                  5                  1.0                    2.0                  NaN                   8.0                        2                      3
3  9ad79ef6-a38d-eec0-14ef-ab987cd94308  2018-01-12       NaN  999-71-4164      NaN       NaN     NaN      Lana840    Maggio310     NaN     NaN      NaN  white  nonhispanic      F   Southbridge  Massachusetts  US  130 Rodriguez Overpass Apt 96       Lowell  Massachusetts  Middlesex County  25017.0  1850  42.617935 -71.305313             11337.43               316.41   42817          8.0                 2               19                        1                  4                  NaN                    NaN                  NaN                   NaN                        2                      1
4  e6012a16-d3a8-4cbd-a4a2-f94ae5c48685  2016-05-07       NaN  999-53-5147      NaN       NaN     NaN       Chu728    Corwin846     NaN     NaN      NaN  white  nonhispanic      F       Belmont  Massachusetts  US   559 Greenfelder Manor Apt 45      Holyoke  Massachusetts    Hampden County  25013.0  1040  42.165733 -72.657553              3185.21             28674.85   24016         10.0                 7               34                        4                  5                  3.0                    2.0                  3.0                  10.0                        2                      3

In [19]:
# 1.1	Import the air quality dataset and familiarize yourself with this dataset. Print the number of counties for which the data is available.

display(air_pollution.head())
print(air_pollution["County"].value_counts())

     County  Year  Measurement_avg pm25
0  Abington  2017             10.730195
1  Abington  2018              9.430195
2  Abington  2019              8.730195
3  Abington  2020              8.230195
4  Abington  2021              8.730195

County
Abington       8
Acton          8
Acushnet       8
Adams          8
Agawam         8
              ..
Woburn         8
Worcester      8
Worthington    8
Wrentham       8
Yarmouth       8
Name: count, Length: 351, dtype: int64

In [21]:
air_pollution_summary = air_pollution.groupby("County")["Measurement_avg pm25"].mean().rename("avg_pm25").reset_index()
display(air_pollution_summary.head())

     County  avg_pm25
0  Abington  8.505195
1     Acton  9.050000
2  Acushnet  6.831250
3     Adams  8.909375
4    Agawam  9.467045